//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Web.Servicio_Estacionamiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servicio_Estacionamiento.ISistemaEstacionamiento")]
    public interface ISistemaEstacionamiento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ValidarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ValidarUsuarioResponse")]
        bool ValidarUsuario(string u, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ValidarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ValidarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string u, string p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearUsuarioResponse")]
        bool CrearUsuario(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarUsuarioResponse")]
        bool ModificarUsuario(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> ModificarUsuarioAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarUsuarioResponse")]
        bool EliminarUsuario(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarUsuario", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearEstacionamientoResponse")]
        bool CrearEstacionamiento(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearEstacionamientoResponse")]
        System.Threading.Tasks.Task<bool> CrearEstacionamientoAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarEstacionamientoResponse")]
        bool ModificarEstacionamiento(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarEstacionamientoResponse")]
        System.Threading.Tasks.Task<bool> ModificarEstacionamientoAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarEstacionamientoResponse")]
        bool EliminarEstacionamiento(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarEstacionamiento", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarEstacionamientoResponse")]
        System.Threading.Tasks.Task<bool> EliminarEstacionamientoAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearVehiculoResponse")]
        bool CrearVehiculo(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/CrearVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/CrearVehiculoResponse")]
        System.Threading.Tasks.Task<bool> CrearVehiculoAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarVehiculoResponse")]
        bool ModificarVehiculo(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/ModificarVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/ModificarVehiculoResponse")]
        System.Threading.Tasks.Task<bool> ModificarVehiculoAsync(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarVehiculoResponse")]
        bool EliminarVehiculo(string xmlEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISistemaEstacionamiento/EliminarVehiculo", ReplyAction="http://tempuri.org/ISistemaEstacionamiento/EliminarVehiculoResponse")]
        System.Threading.Tasks.Task<bool> EliminarVehiculoAsync(string xmlEmp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISistemaEstacionamientoChannel : Biblioteca.Web.Servicio_Estacionamiento.ISistemaEstacionamiento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SistemaEstacionamientoClient : System.ServiceModel.ClientBase<Biblioteca.Web.Servicio_Estacionamiento.ISistemaEstacionamiento>, Biblioteca.Web.Servicio_Estacionamiento.ISistemaEstacionamiento {
        
        public SistemaEstacionamientoClient() {
        }
        
        public SistemaEstacionamientoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SistemaEstacionamientoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaEstacionamientoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SistemaEstacionamientoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ValidarUsuario(string u, string p) {
            return base.Channel.ValidarUsuario(u, p);
        }
        
        public System.Threading.Tasks.Task<bool> ValidarUsuarioAsync(string u, string p) {
            return base.Channel.ValidarUsuarioAsync(u, p);
        }
        
        public bool CrearUsuario(string xmlEmp) {
            return base.Channel.CrearUsuario(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(string xmlEmp) {
            return base.Channel.CrearUsuarioAsync(xmlEmp);
        }
        
        public bool ModificarUsuario(string xmlEmp) {
            return base.Channel.ModificarUsuario(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarUsuarioAsync(string xmlEmp) {
            return base.Channel.ModificarUsuarioAsync(xmlEmp);
        }
        
        public bool EliminarUsuario(string xmlEmp) {
            return base.Channel.EliminarUsuario(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(string xmlEmp) {
            return base.Channel.EliminarUsuarioAsync(xmlEmp);
        }
        
        public bool CrearEstacionamiento(string xmlEmp) {
            return base.Channel.CrearEstacionamiento(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> CrearEstacionamientoAsync(string xmlEmp) {
            return base.Channel.CrearEstacionamientoAsync(xmlEmp);
        }
        
        public bool ModificarEstacionamiento(string xmlEmp) {
            return base.Channel.ModificarEstacionamiento(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarEstacionamientoAsync(string xmlEmp) {
            return base.Channel.ModificarEstacionamientoAsync(xmlEmp);
        }
        
        public bool EliminarEstacionamiento(string xmlEmp) {
            return base.Channel.EliminarEstacionamiento(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarEstacionamientoAsync(string xmlEmp) {
            return base.Channel.EliminarEstacionamientoAsync(xmlEmp);
        }
        
        public bool CrearVehiculo(string xmlEmp) {
            return base.Channel.CrearVehiculo(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> CrearVehiculoAsync(string xmlEmp) {
            return base.Channel.CrearVehiculoAsync(xmlEmp);
        }
        
        public bool ModificarVehiculo(string xmlEmp) {
            return base.Channel.ModificarVehiculo(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> ModificarVehiculoAsync(string xmlEmp) {
            return base.Channel.ModificarVehiculoAsync(xmlEmp);
        }
        
        public bool EliminarVehiculo(string xmlEmp) {
            return base.Channel.EliminarVehiculo(xmlEmp);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVehiculoAsync(string xmlEmp) {
            return base.Channel.EliminarVehiculoAsync(xmlEmp);
        }
    }
}
