//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARRIENDO
    {
        public ARRIENDO()
        {
            this.DETALLE_ARRIENDO = new HashSet<DETALLE_ARRIENDO>();
        }
    
        public string COD_ARRIENDO { get; set; }
        public string PATENTE { get; set; }
        public string COD_ESTACIONAMIENTO { get; set; }
        public System.DateTime FECHA_ARRIENDO { get; set; }
        public bool PAGADO { get; set; }
    
        public virtual ESTACIONAMIENTO ESTACIONAMIENTO { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
        public virtual ICollection<DETALLE_ARRIENDO> DETALLE_ARRIENDO { get; set; }
    }
}
