//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTACIONAMIENTO
    {
        public ESTACIONAMIENTO()
        {
            this.ARRIENDO = new HashSet<ARRIENDO>();
        }
    
        public string COD_ESTACIONAMIENTO { get; set; }
        public string RUT_USUARIO { get; set; }
        public string DIRECCION { get; set; }
        public int PRECIO_HORA { get; set; }
        public int SUPERFICIE { get; set; }
        public int ALTURA { get; set; }
        public bool HABILITADO { get; set; }
    
        public virtual ICollection<ARRIENDO> ARRIENDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
