//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ESTACIONAMIENTO = new HashSet<ESTACIONAMIENTO>();
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public string RUT_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string APELLIDO_USUARIO { get; set; }
        public string CORREO_USUARIO { get; set; }
        public int TELEFONO_USUARIO { get; set; }
        public string DIRECCION_USUARIO { get; set; }
        public int ID_TIPO_CUENTA { get; set; }
        public int ID_TIPO_BANCO { get; set; }
        public long NUMERO_CUENTA_BANCARIA { get; set; }
        public int CVV { get; set; }
        public int ID_TIPO_USUARIO { get; set; }
        public bool HABILITADO { get; set; }
    
        public virtual ICollection<ESTACIONAMIENTO> ESTACIONAMIENTO { get; set; }
        public virtual TIPO_BANCO TIPO_BANCO { get; set; }
        public virtual TIPO_CUENTA TIPO_CUENTA { get; set; }
        public virtual TIPO_USUARIO TIPO_USUARIO { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
